version: 2.1

orbs:
  android: circleci/android@2.0
  gradle: circleci/gradle@2.2

executors:
  android:
    docker:
      - image: cimg/android:2022.04

jobs:
  build:
    executor: android
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Building the APK
                command: ./gradlew -s assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk

workflows:
  test-build:
    jobs:
      - build
      - gradle/test:
          executor: android
          test_command: test --stacktrace
          test_results_path: app/build/reports/tests